### PR TITLE
feat: update Go to 1.19

### PR DESCRIPTION
**Pull request by smira**
See https://go.dev/doc/go1.19

Signed-off-by: Andrey Smirnov <andrey.smirnov@talos-systems.com>

### CODE REVIEW

**Comment by smira** [comment]
image is not published yet, so the build fails

**Review by frezbo — APPROVED** [review]

**Comment by DmitriyMV** [comment]
Fails on linters - probably should wait for https://github.com/golangci/golangci-lint/pull/3037

**Comment by smira** [comment]
> It now fails on linters - probably should wait for [golangci/golangci-lint#3037](https://github.com/golangci/golangci-lint/pull/3037)

it works when installed from source (so compiled with Go 1.19), I got build instructions updated

**Pull request merged**
