### PR TITLE
chore: bump deps

### PR DESCRIPTION
**Pull request by DmitriyMV**
Bump node version.

Signed-off-by: Dmitriy Matrenichev <dmitry.matrenichev@siderolabs.com>

### CODE REVIEW

**Review by utkuozdemir — APPROVED** [review]
Maybe sme time we can configure renovatebot here? cc: @frezbo

**Review by smira — APPROVED** [review]
we should regen kres own build instructions, in other words rekres kres itself

**Comment by DmitriyMV** [comment]
@smira yep, sorry - missed that during commit. FIxed!

**Pull request merged**
