### PR TITLE
feat: add support for make conformance

### LINKED ISSUE #50: add suport for `make conformance`
So that we could validate conformance before CI

### PR DESCRIPTION
**Pull request by sauterp**
We generate a make command that executes the conformance container on
the repository.

Fixes #50

Signed-off-by: Philipp Sauter <philipp.sauter@siderolabs.com>

### CODE REVIEW

**Review by frezbo — APPROVED** [review]

**Review by smira — APPROVED** [review]

**Comment by smira** [comment]
I wonder if your local checkout is using `main` branch now

**Comment by sauterp** [comment]
> I wonder if your local checkout is using `main` branch now

yes I had to rename it on my fork aswell.

**Review by smira — APPROVED** [review]

**Pull request merged**
