### PR TITLE
feat: support pushing stable image tags

### PR DESCRIPTION
**Pull request by Unix4ever**
Push stable tags when building tagged refs which don't contain beta or alpha strings.

### CODE REVIEW

**Comment by smira** [comment]
I don't think it's going to work.

If you release v0.2.0, and then v0.1.1, it would mark v0.1.1 as stable.

I don't know what the proper solution is, but it doesn't seem to be this one.

**Comment by Unix4ever** [comment]
ah, right 😕  backports will break it.

**Comment by Unix4ever** [comment]
I guess it's more complicated then. Need to get the current tag, parse it's semver, get current stable tag pushed to the registry and compare them.

**Comment by smira** [comment]
I don't like the idea of `stable` which is automated this way (the latest tag becomes stable), as it feels like we somehow pretend that the version was extensively tested and it's now stable.

We should probably fix `:latest` not to push from release branches (if not already the fact?). But `:latest` doesn't have a feeling of a stable release, it's just  latest.

In theory we could mark something as stable as it goes into the SaaS, but we need to get the flow going I guess.

**Pull request closed without merging**
