### PR TITLE
fix: release for api only projects

### PR DESCRIPTION
**Pull request by frezbo**
For api projects only publish RELEASE notes.

### CODE REVIEW

**Comment by smira** [comment]
I still don't get it... even the API projects have some artifacts that get uploaded, even sha256sum.txt gets uploaded. I think the bug is not in the missing artifacts

**Comment by smira** [comment]
e.g. https://github.com/siderolabs/go-kubernetes/releases/tag/v0.2.6 this one failed in the CI, but it has _some_ artifacts

**Comment by frezbo** [comment]
> I still don't get it... even the API projects have some artifacts that get uploaded, even sha256sum.txt gets uploaded. I think the bug is not in the missing artifacts

i mean, we don't need those right, it's just creating a shasum files of coverage.txt, so no point in publishing them

**Comment by smira** [comment]
> > I still don't get it... even the API projects have some artifacts that get uploaded, even sha256sum.txt gets uploaded. I think the bug is not in the missing artifacts
> 
> i mean, we don't need those right, it's just creating a shasum files of coverage.txt, so no point in publishing them

That's a second question, idk, it might be useful or not, but it doesn't hurt. 

But the problem is that release step is broken in some way.

**Comment by frezbo** [comment]
> But the problem is that release step is broken in some way.

yes, but it mostly on the shasums, so we can disable for api only projects

**Comment by smira** [comment]
> > But the problem is that release step is broken in some way.
> 
> yes, but it mostly on the shasums, so we can disable for api only projects

sorry, but I don't see how it will be any better for other projects? if the project provides real assets, the release step will fail same way, so we need to fix the release step?

**Comment by frezbo** [comment]
> > > But the problem is that release step is broken in some way.
> > 
> > 
> > yes, but it mostly on the shasums, so we can disable for api only projects
> 
> sorry, but I don't see how it will be any better for other projects? if the project provides real assets, the release step will fail same way, so we need to fix the release step?

never saw it fail for others :sweat_smile: , I'll try again in roller-derby

**Review by smira — APPROVED** [review]

**Pull request merged**
